import React from 'react';
import ReactDOM from 'react-dom/client';
import AdminAddCategory from './AdminAddCategory';
import AdminAddProduct from './AdminAddProduct';
import AdminCategory from './AdminCategory';
import AdminChangePassword from './AdminChangePassword';
import AdminDashBoard from './AdminDashboard';
import AdminEditCategory from './AdminEditCategory';
import AdminEditProduct from './AdminEditProduct';
import AdminForgotPassword from './AdminForgotPassword';
import AdminLogin from './AdminLogin';
import AdminOrder from './AdminOrder';
import AdminProductOrder from './AdminPrintOrder';
import AdminProduct from './AdminProduct';
import AdminUser from './AdminUser';
import AdminViewProduct from './AdminViewProduct';
import AdminViewOrder from './AdminViewOrder';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<AdminViewOrder />);